const products = [
  // ===== BEST SELLER =====
  {
    id: 0.1,
    name: "Women's Desk-to-Dinner Cotton Stretch Formal Shirt",
    slug: "womens-desk-to-dinner-formal-shirt",
    description: "Smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place.",
    discount: 30,
    price: 99.99,
    listPrice: 69.99,
    images: [
      "https://m.media-amazon.com/images/I/61eZiSLbBpL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71rbrJS2RjL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Shirts",
    brand: "Shirk",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.12,
    name: "VERO MODA Women's Solid V-Neck Top",
    slug: "vero-moda-women-vneck-top",
    description: "Smart cuffs on the sleeves. The front placket includes a discreet design.",
    discount: 50,
    price: 99.99,
    listPrice: 49.99,
    images: [
      "https://m.media-amazon.com/images/I/61xP21EWQSL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61AxjZNo-RL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Shirts",
    brand: "Vero Moda",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.3,
    name: "ABSOLUTE DEFENSE Oversize Tshirt Baggy for Women",
    slug: "absolute-defense-oversize-tshirt-women",
    description: "Casual stylish oversized tshirt for women.",
    discount: 70,
    price: 199.99,
    listPrice: 79.99,
    images: [
      "https://m.media-amazon.com/images/I/51ZWI+GJMqL._SY606_.jpg",
      "https://m.media-amazon.com/images/I/41XEl03GaUL._SY606_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Gucci",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.000003,
    name: "FLEXIMAA Women's Cotton Plain Round Neck Half Sleeve Combo T-Shirt",
    slug: "fleximaa-women-cotton-tshirt-combo",
    description: "Comfortable combo t-shirt for everyday wear.",
    discount: 50,
    price: 89.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71nir3RRdFL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/8198bn3h8BL._SX679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Fleximaa",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.00003,
    name: "Workout Quick Dry Gym Wear for Women Running T-Shirt",
    slug: "workout-quick-dry-gym-tshirt-women",
    description: "Quick dry gym wear for women.",
    discount: 50,
    price: 49.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/61lS4daJ4NL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61B22OjLnxL._SX679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Gucci",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.03,
    name: "Nike Women's Cotton Checkered Regular Fit T-Shirt",
    slug: "nike-women-checkered-tshirt",
    description: "Nike checkered regular fit t-shirt for women.",
    discount: 40,
    price: 49.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/61GZW38F9cL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61ntGj5YPNL._SY679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Nike",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 2,
    name: "Lymio Men's Loose Denim Shirt Baggy",
    slug: "lymio-mens-loose-denim-shirt-baggy",
    description: "Baggy oversized denim shirt for men.",
    discount: 80,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71CrMJ6GZRL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71sqVxaJvQL._SY679_.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Levi's",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.22,
    name: "Levi's Women's Slim Jeans",
    slug: "levis-womens-slim-jeans",
    description: "Classic slim fit jeans from Levi's for women.",
    discount: 90,
    price: 49.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71ohU2gJzbL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71IP3JQ7ivL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.003,
    name: "Women's Slim Jeans Stylish",
    slug: "womens-slim-jeans-stylish",
    description: "Stylish slim jeans for women.",
    discount: 70,
    price: 49.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71ODjrA3j7L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81hhPteNpWL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.0003,
    name: "Miss Chase Women's Skinny Fit High Rise Stretchable Denim Jeans",
    slug: "miss-chase-womens-skinny-fit-jeans",
    description: "Skinny fit high rise stretchable denim jeans for women.",
    discount: 55,
    price: 69.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71LAQDR38NL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/81P78nXN9PL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Miss Chase",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 1,
    name: "Fossil Men's Chronograph Stainless Steel Watch",
    slug: "fossil-men-chronograph-watch",
    description: "Classic analog men's watch with premium finish.",
    discount: 45,
    price: 129.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iBYW8bvPL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Fossil",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["black", "brown"],
    sizes: [],
    reviews: [],
  },
  {
    id: 3,
    name: "Maniac Men's Solid Collared Knitted Sneaker Shoes",
    slug: "maniac-mens-knitted-sneaker-shoes",
    description: "Stylish knitted sneaker shoes for men.",
    discount: 58,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71VyVqTJetL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71BoKTLJmsL._SY500_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Adidas",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 4,
    name: "Lymio Men's Fit T-Shirts Denim Style Baggy",
    slug: "lymio-mens-fit-tshirts-baggy",
    description: "Baggy oversized denim style t-shirts for men.",
    discount: 79,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/61GZW38F9cL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61ntGj5YPNL._SY679_.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 5,
    name: "Lymio Men's Loose Denim Jeans Baggy",
    slug: "lymio-mens-loose-denim-jeans-baggy",
    description: "Baggy oversized denim jeans for men.",
    discount: 45,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71ohU2gJzbL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71IP3JQ7ivL._SX522_.jpg",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 6,
    name: "Lymio Men's Loose Casual Shirts Baggy",
    slug: "lymio-mens-loose-casual-shirts-baggy",
    description: "Baggy casual shirts for men.",
    discount: 85,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71CrMJ6GZRL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71sqVxaJvQL._SY679_.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Tom Ford",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 7,
    name: "Lymio Men's Loose Oversized Shirts Baggy",
    slug: "lymio-mens-loose-oversized-shirts-baggy",
    description: "Baggy oversized shirts for men.",
    discount: 90,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/61CZGlXcvML._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71CrMJ6GZRL._SY679_.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Tom Ford",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // ===== NEW ARRIVAL =====
  {
    id: 8,
    name: "Noble Monk Men's Solid Casual Full Sleeve Shirt",
    slug: "noble-monk-mens-solid-casual-shirt",
    description: "Full sleeve casual shirt for men.",
    discount: 79,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51We0y6ETSL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/41wQ9SDN71L._SY625_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Puma",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 9,
    name: "Fossil Nate Chronograph Analog Black Dial Men's Watch",
    slug: "fossil-nate-chronograph-mens-watch",
    description: "Fossil Nate Chronograph Watch for Men.",
    discount: 80,
    price: 149.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iBYW8bvPL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Watches",
    brand: "Fossil",
    tags: ["new-arrival", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: [],
    reviews: [],
  },
  {
    id: 10,
    name: "Classic Moccasins Non-Lace Formal Shoes for Men",
    slug: "classic-moccasins-formal-shoes-men",
    description: "Classic formal shoes for office, party and wedding.",
    discount: 30,
    price: 129.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/419vnRwtJnL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/61qyumEgw2L._SY675_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Levi's",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4,
    numReviews: 6,
    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 11,
    name: "Centrino Men's Classic Moccasins Formal Shoes for Office",
    slug: "centrino-mens-classic-moccasins-formal-shoes",
    description: "Classic moccasins formal shoes for men.",
    discount: 40,
    price: 149.99,
    listPrice: 0,
    images: [
      "https://images.pexels.com/photos/19090/pexels-photo.jpg",
      "https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Centrino",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 12,
    name: "Symbol Premium Men's Slim Fit Stretchable Jeans",
    slug: "symbol-premium-mens-slim-fit-jeans",
    description: "Air-Lite hollow fiber jeans for comfort and style.",
    discount: 55,
    price: 149.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71ohU2gJzbL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71IP3JQ7ivL._SX522_.jpg",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Symbol",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 13,
    name: "Ben Martin Men's Relaxed Fit Jeans",
    slug: "ben-martin-mens-relaxed-fit-jeans",
    description: "Comfortable relaxed fit denim jeans for men.",
    discount: 60,
    price: 149.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71ODjrA3j7L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81hhPteNpWL._SX522_.jpg",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Ben Martin",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // ===== TODAY'S DEAL =====
  {
    id: 14,
    name: "Ben Martin Men's Regular Fit Stretchable Brown Denim Jeans",
    slug: "ben-martin-mens-regular-fit-brown-jeans",
    description: "Stretch-cotton casual jeans for all-day comfort.",
    discount: 30,
    price: 59.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71LAQDR38NL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/81P78nXN9PL._SY679_.jpg",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Gucci",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 13,
    countInStock: 40,
    colors: ["black", "white"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 15,
    name: "Red Chief Genuine Leather Derby Lace Up Formal Shoes for Men",
    slug: "red-chief-leather-derby-formal-shoes-men",
    description: "Genuine leather derby lace up formal shoes for office.",
    discount: 80,
    price: 29.99,
    listPrice: 0,
    images: [
      "https://images.pexels.com/photos/19090/pexels-photo.jpg",
      "https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Puma",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 16,
    name: "Lymio Men's Loose Baggy Denim Jeans",
    slug: "lymio-mens-loose-baggy-denim-jeans",
    description: "Baggy oversized denim jeans for men.",
    discount: 80,
    price: 229.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/81hhPteNpWL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71ODjrA3j7L._SX522_.jpg",
    ],
    gender: "Men",
    category: "Jeans",
    brand: "Gucci",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 17,
    name: "Lymio Polo T Shirt for Men Casual T-Shirt",
    slug: "lymio-polo-tshirt-men-casual",
    description: "Casual polo t-shirt for men.",
    discount: 90,
    price: 329.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/61GZW38F9cL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61ntGj5YPNL._SY679_.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 18,
    name: "Lymio Men's Premium Casual T-Shirt",
    slug: "lymio-mens-premium-casual-tshirt",
    description: "Premium casual t-shirt for men.",
    discount: 20,
    price: 329.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51ZWI+GJMqL._SY606_.jpg",
      "https://m.media-amazon.com/images/I/41XEl03GaUL._SY606_.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 19,
    name: "POLO Men's Wonder T-Shirts",
    slug: "polo-mens-wonder-tshirts",
    description: "Sports running t-shirts for men.",
    discount: 25,
    price: 99.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71nir3RRdFL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/8198bn3h8BL._SX679_.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Burberry",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // ===== FEATURED =====
  {
    id: 20,
    name: "Urbano Fashion Men's Cotton Full Sleeve Regular Fit Casual Solid Shirt",
    slug: "urbano-fashion-mens-casual-solid-shirt",
    description: "Regular fit casual solid shirt for men.",
    discount: 56,
    price: 329.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/71CrMJ6GZRL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61CZGlXcvML._SY679_.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Levi's",
    tags: ["featured", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 21,
    name: "Titan Men's Analog Watch",
    slug: "titan-mens-analog-watch",
    description: "Elegant men's watch with leather strap.",
    discount: 59,
    price: 329.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iBYW8bvPL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Watches",
    brand: "Titan",
    tags: ["featured", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: [],
    reviews: [],
  },
  {
    id: 22,
    name: "ASIAN Men's Wonder Sports Running Shoes",
    slug: "asian-mens-wonder-sports-running-shoes",
    description: "Sports running shoes for men.",
    discount: 68,
    price: 329.99,
    listPrice: 0,
    images: [
      "https://m.media-amazon.com/images/I/51We0y6ETSL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/41wQ9SDN71L._SY625_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Nike",
    tags: ["featured"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,
    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // ===== WOMEN'S FOOTWEAR =====
  {
    id: 101,
    name: "Symbol Premium Women's Slingback Pumps",
    slug: "symbol-premium-womens-slingback-pumps",
    description: "Elegant stiletto heels for evening and formal wear.",
    discount: 60,
    price: 49.99,
    listPrice: 79.99,
    images: [
      "https://m.media-amazon.com/images/I/71oQDjYj8WL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/71ze+WIO75L._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Bella Vogue",
    tags: ["best-seller", "heels"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 18,
    numSales: 42,
    countInStock: 25,
    colors: ["black", "red", "nude"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 1001,
    name: "Elegant Stiletto Heels for Women",
    slug: "elegant-stiletto-heels-women",
    description: "Sophisticated stiletto heels for evening events.",
    discount: 70,
    price: 79.99,
    listPrice: 99.99,
    images: [
      "https://m.media-amazon.com/images/I/71kZwI4bP2L._SY675_.jpg",
      "https://m.media-amazon.com/images/I/711P1VE-4EL._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Bella Vogue",
    tags: ["best-seller", "heels"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 18,
    numSales: 42,
    countInStock: 25,
    colors: ["black", "red", "nude"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 102,
    name: "Vendoz Women Stylish Cream Flat Sandals",
    slug: "vendoz-women-cream-flat-sandals",
    description: "Comfortable minimalist flats for everyday wear.",
    discount: 80,
    price: 34.99,
    listPrice: 49.99,
    images: [
      "https://m.media-amazon.com/images/I/61yZsOC22AL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51ZuIZhmfhL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanFeet",
    tags: ["flat", "everyday"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "beige"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 1002,
    name: "Vendoz Women Stylish White Flat Sandals",
    slug: "vendoz-women-white-flat-sandals",
    description: "Minimalist flats for everyday casual walking.",
    discount: 50,
    price: 34.99,
    listPrice: 49.99,
    images: [
      "https://m.media-amazon.com/images/I/51BdzBgSVbL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/61f1ydF7whL._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanFeet",
    tags: ["flat", "everyday", "best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "beige"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 103,
    name: "Beach Vibe Summer Sandals for Women",
    slug: "beach-vibe-summer-sandals-women",
    description: "Lightweight sandals for beach and casual summer days.",
    discount: 70,
    price: 27.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/51lHLRorDPL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51bxzQP4O1L._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "SunWalk",
    tags: ["summer", "sandals"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 9,
    numSales: 21,
    countInStock: 36,
    colors: ["yellow"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 104,
    name: "Chunky White Sneakers for Women",
    slug: "chunky-white-sneakers-women",
    description: "Modern chunky sneakers for streetwear style.",
    discount: 79,
    price: 59.99,
    listPrice: 79.99,
    images: [
      "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
      "https://images.pexels.com/photos/1204464/pexels-photo-1204464.jpeg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "StepMax",
    tags: ["sneakers", "white"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 15,
    numSales: 37,
    countInStock: 50,
    colors: ["white", "gray"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 105,
    name: "Bacca Bucci Men Lace Up Sneaker Shoes",
    slug: "bacca-bucci-men-lace-up-sneakers",
    description: "Genuine leather ankle boots for a chic look.",
    discount: 90,
    price: 89.99,
    listPrice: 119.99,
    images: [
      "https://m.media-amazon.com/images/I/419vnRwtJnL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/61qyumEgw2L._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "TimberLane",
    tags: ["boots", "leather", "best-seller"],
    isPublished: true,
    avgRating: 4.9,
    numReviews: 22,
    numSales: 51,
    countInStock: 20,
    colors: ["brown", "black"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 106,
    name: "Beach Vibe Fancy Sandals for Women",
    slug: "beach-vibe-fancy-sandals-women",
    description: "Lightweight breathable sandals for beach outings.",
    discount: 30,
    price: 27.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/71oFITJVMyL._SY695_.jpg",
      "https://m.media-amazon.com/images/I/71e6tMleftL._SY695_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "SunWalk",
    tags: ["summer", "sandals"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 9,
    numSales: 21,
    countInStock: 36,
    colors: ["tan", "yellow"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 107,
    name: "Symbol Premium Mens Smart Casual Flat Leather Sneakers",
    slug: "symbol-premium-mens-smart-casual-sneakers",
    description: "Stylish flat leather sneakers for urban wear.",
    discount: 80,
    price: 49.99,
    listPrice: 59.99,
    images: [
      "https://m.media-amazon.com/images/I/71z0J06321L._SY675_.jpg",
      "https://m.media-amazon.com/images/I/71sX2acqoXL._SY675_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "StrideX",
    tags: ["sneakers", "casual"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 14,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "pink"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 108,
    name: "TRASE Block Heels Sandals For Women",
    slug: "trase-block-heels-sandals-women",
    description: "Elegant block heels for work or evening outings.",
    discount: 40,
    price: 59.99,
    listPrice: 74.99,
    images: [
      "https://m.media-amazon.com/images/I/6159+SakRPL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61HWG-3wmBL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "ChicLift",
    tags: ["heels", "formal", "best-seller"],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 12,
    numSales: 28,
    countInStock: 25,
    colors: ["black", "beige"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 109,
    name: "XE Looks Pencil Heel Fashion Bellies for Women",
    slug: "xe-looks-pencil-heel-bellies-women",
    description: "Stylish pencil heel bellies for women.",
    discount: 30,
    price: 22.99,
    listPrice: 34.99,
    images: [
      "https://m.media-amazon.com/images/I/713Pa9SyWKL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61Cmavzy24L._SY500_.jpg",
    ],
    gender: "Women",
    category: "Flats",
    brand: "GreenStep",
    tags: ["eco", "flats", "boho"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 8,
    numSales: 19,
    countInStock: 30,
    colors: ["brown", "cream"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 110,
    name: "Campus Women Ogl-13 Sneakers",
    slug: "campus-women-ogl13-sneakers",
    description: "Platform sneakers for bold fashion statement.",
    discount: 40,
    price: 64.99,
    listPrice: 89.99,
    images: [
      "https://m.media-amazon.com/images/I/61MZ4xj-gXL._SY575_.jpg",
      "https://m.media-amazon.com/images/I/61B876acE+L._SY575_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "VoltWear",
    tags: ["platform", "trendy"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 16,
    numSales: 42,
    countInStock: 50,
    colors: ["white", "purple"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },

  // ===== MEN'S FOOTWEAR =====
  {
    id: 111,
    name: "Urban Trek Sandals for Men",
    slug: "urban-trek-sandals-men",
    description: "Durable sandals for outdoor adventures and summer.",
    discount: 20,
    price: 32.99,
    listPrice: 45.99,
    images: [
      "https://m.media-amazon.com/images/I/51xWMRRtdPL._SX500_.jpg",
      "https://m.media-amazon.com/images/I/71AHiOZHshL._SY500_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "TrailFlex",
    tags: ["outdoor", "sandals"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 11,
    numSales: 30,
    countInStock: 42,
    colors: ["brown", "black"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 112,
    name: "Puma Men Galaxis Pro Running Shoe",
    slug: "puma-men-galaxis-pro-running-shoe",
    description: "High-performance running sneakers for comfort and breathability.",
    discount: 30,
    price: 58.49,
    listPrice: 69.99,
    images: [
      "https://m.media-amazon.com/images/I/51We0y6ETSL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/41wQ9SDN71L._SY625_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "Puma",
    tags: ["running", "fitness", "best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 15,
    numSales: 41,
    countInStock: 50,
    colors: ["yellow", "white"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 113,
    name: "Casual Street Loafers for Men",
    slug: "casual-street-loafers-men",
    description: "Smart-casual loafers for jeans or chinos.",
    discount: 40,
    price: 39.99,
    listPrice: 49.99,
    images: [
      "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg",
      "https://images.pexels.com/photos/191829/pexels-photo-191829.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "UrbanStep",
    tags: ["casual", "loafers"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 7,
    numSales: 22,
    countInStock: 35,
    colors: ["navy", "grey"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 114,
    name: "Office Classic Formal Shoes for Men",
    slug: "office-classic-formal-shoes-men",
    description: "Polished leather formal shoes for business attire.",
    discount: 40,
    price: 74.99,
    listPrice: 89.99,
    images: [
      "https://images.pexels.com/photos/19090/pexels-photo.jpg",
      "https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "EliteStep",
    tags: ["formal", "leather"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 18,
    numSales: 50,
    countInStock: 45,
    colors: ["black", "brown"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 115,
    name: "Campus Men Crysta Pro Running Shoes",
    slug: "campus-men-crysta-pro-running-shoes",
    description: "Breathable canvas sneakers for everyday errands.",
    discount: 70,
    price: 29.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/71VyVqTJetL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71BoKTLJmsL._SY500_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "EaseWear",
    tags: ["casual", "canvas", "today-deal"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 6,
    numSales: 17,
    countInStock: 28,
    colors: ["grey", "white"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },

  // ===== WOMEN'S SNEAKERS / CASUAL =====
  {
    id: 201,
    name: "YOHO Street Women's Trendy Dual-Tone Casual Shoes",
    slug: "yoho-street-women-dual-tone-casual-shoes",
    description: "Trendy casual shoes for everyday women's wear.",
    discount: 80,
    price: 29.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/61xeemurkoL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61hXGcQXMmL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "EaseWear",
    tags: ["casual", "canvas", "today-deal"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 6,
    numSales: 17,
    countInStock: 28,
    colors: ["grey", "white"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
  {
    id: 202,
    name: "Fashionable Slip-On Ballet Flats for Women",
    slug: "fashionable-slip-on-ballet-flats-women",
    description: "Elegant ballet flats for daily and office wear.",
    discount: 70,
    price: 35.5,
    listPrice: 45.0,
    images: [
      "https://m.media-amazon.com/images/I/61vYvoETE0L._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51Y+20SVRoL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Flats",
    brand: "FemStyle",
    tags: ["flats", "classic", "today-deal"],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 10,
    numSales: 25,
    countInStock: 50,
    colors: ["black", "beige"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 203,
    name: "Women Alexa Running Shoes",
    slug: "women-alexa-running-shoes",
    description: "Lightweight running shoes for active lifestyles.",
    discount: 80,
    price: 49.99,
    listPrice: 60.0,
    images: [
      "https://m.media-amazon.com/images/I/516x4VqF5GL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/61xJ4x87GJL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "ActivePro",
    tags: ["running", "sport", "today-deal"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 18,
    numSales: 40,
    countInStock: 40,
    colors: ["pink", "white", "grey"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 204,
    name: "Loafers for Women Comfortable Block Heeled Fashion Moccasins",
    slug: "women-comfortable-block-heeled-moccasins",
    description: "Stylish loafers for casual and formal occasions.",
    discount: 60,
    price: 59.99,
    listPrice: 75.0,
    images: [
      "https://m.media-amazon.com/images/I/61aIyIcz4fL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/6175BMTCMoL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "GlamourStep",
    tags: ["heels", "party", "elegant"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 30,
    colors: ["red", "black"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 2040,
    name: "YOHO Bliss Slip-on Loafers for Women",
    slug: "yoho-bliss-slip-on-loafers-women",
    description: "Comfortable slip-on loafers for casual and formal wear.",
    discount: 30,
    price: 49.99,
    listPrice: 75.0,
    images: [
      "https://m.media-amazon.com/images/I/61G5rifrdFL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61aGBtWc9qL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "GlamourStep",
    tags: ["heels", "party", "today-deal"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 30,
    colors: ["red", "black"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 205,
    name: "Doctor Walk Women's Comfort Slip-On Loafers",
    slug: "doctor-walk-women-comfort-slip-on-loafers",
    description: "Soft slip-on loafers for comfort and casual office looks.",
    discount: 70,
    price: 42.0,
    listPrice: 50.0,
    images: [
      "https://m.media-amazon.com/images/I/71vO1UM63iL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81aoj5RJHtL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanWalk",
    tags: ["loafers", "today-deal"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 9,
    numSales: 15,
    countInStock: 35,
    colors: ["brown", "black"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },

  // ===== ACCESSORIES =====
  {
    id: 301,
    name: "VINCENT CHASE EYEWEAR Women's Polarized Cateye Sunglasses",
    slug: "vincent-chase-women-cateye-sunglasses",
    description: "UV-protected cateye sunglasses for women.",
    discount: 30,
    price: 49.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/51kK+tz-KvL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61S5o9smoEL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Accessories",
    brand: "SunChic",
    tags: ["sunglasses", "fashion", "today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 14,
    numSales: 30,
    countInStock: 40,
    colors: ["black", "brown"],
    sizes: [],
    reviews: [],
  },
  {
    id: 3010,
    name: "Full Rim Square Polarized Unisex Sunglasses",
    slug: "full-rim-square-polarized-unisex-sunglasses",
    description: "UV-protected square sunglasses for men and women.",
    discount: 90,
    price: 49.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/41xXYvjCdyL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/519GMvo9tqL.jpg",
    ],
    gender: "Women",
    category: "Accessories",
    brand: "SunChic",
    tags: ["sunglasses", "fashion", "today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 14,
    numSales: 30,
    countInStock: 40,
    colors: ["black", "brown"],
    sizes: [],
    reviews: [],
  },
  {
    id: 302,
    name: "HIGH TOUCH Leather Women's Handbag Shoulder Bag",
    slug: "high-touch-leather-women-handbag",
    description: "Elegant spacious leather handbag for daily use.",
    discount: 70,
    price: 79.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/91PORHaaBUL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81ZERwn3qbL._SY535_.jpg",
    ],
    gender: "Women",
    category: "Handbags",
    brand: "UrbanStyle",
    tags: ["handbag", "today-deal", "fashion"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 20,
    numSales: 25,
    countInStock: 25,
    colors: ["black", "tan"],
    sizes: [],
    reviews: [],
  },
  {
    id: 3020,
    name: "Lavie Luxe Women's Satchel Handbag for Work",
    slug: "lavie-luxe-women-satchel-handbag",
    description: "Stylish satchel handbag for work and gifting.",
    discount: 60,
    price: 79.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/71U++aoO+cL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81IJTHuZlaL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Handbags",
    brand: "Lavie",
    tags: ["handbag", "today-deal", "fashion"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 20,
    numSales: 25,
    countInStock: 25,
    colors: ["black", "tan"],
    sizes: [],
    reviews: [],
  },
  {
    id: 303,
    name: "Bacca Bucci Men's Reversible Genuine Leather Belt",
    slug: "bacca-bucci-men-reversible-leather-belt",
    description: "Durable reversible leather belt for formal and casual wear.",
    discount: 30,
    price: 65.0,
    listPrice: 45.0,
    images: [
      "https://m.media-amazon.com/images/I/61s1etnxiUL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/6110zfAb-rL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Bacca Bucci",
    tags: ["belt", "today-deal", "classic"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 50,
    colors: ["brown", "black"],
    sizes: [],
    reviews: [],
  },
  {
    id: 304,
    name: "Titan Karishma Analog Black Dial Men's Watch",
    slug: "titan-karishma-analog-men-watch",
    description: "Elegant analog men's watch by Titan.",
    discount: 60,
    price: 129.99,
    listPrice: 150.0,
    images: [
      "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iBYW8bvPL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Watches",
    brand: "Titan",
    tags: ["watch", "today-deal", "analog"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 30,
    numSales: 45,
    countInStock: 30,
    colors: ["black", "brown"],
    sizes: [],
    reviews: [],
  },
  {
    id: 305,
    name: "Puma Men's Cap",
    slug: "puma-mens-cap",
    description: "Breathable cotton cap for casual outings and sports.",
    discount: 50,
    price: 19.99,
    listPrice: 25.0,
    images: [
      "https://m.media-amazon.com/images/I/51zDQyDoV0L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51hBciQhASL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Puma",
    tags: ["cap", "cotton", "casual"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 10,
    numSales: 18,
    countInStock: 60,
    colors: ["blue", "grey", "black"],
    sizes: [],
    reviews: [],
  },
  {
    id: 306,
    name: "ANEZKA Unisex Adjustable Baseball Cap",
    slug: "anezka-unisex-adjustable-baseball-cap",
    description: "Breathable cotton baseball cap for sports and casual wear.",
    discount: 60,
    price: 59.99,
    listPrice: 99.0,
    images: [
      "https://m.media-amazon.com/images/I/81C6Gpb6KpL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81SYrxQyISL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "ANEZKA",
    tags: ["cap", "today-deal", "casual"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 10,
    numSales: 18,
    countInStock: 60,
    colors: ["blue", "grey", "black"],
    sizes: [],
    reviews: [],
  },
];